export const faqData = [
    // **Saludos**
    { question: "Hola", answer: "¡Hola! ¿En qué puedo ayudarte hoy?" },
    { question: "¿Que tal?", answer: "¡Todo bien! ¿Y tú?" },
    { question: "Buenas tardes", answer: "Buenas tardes. ¿Cómo puedo asistirte?" },
    { question: "Buenas noches", answer: "Buenas noches. ¿En qué te puedo ayudar?" },
    { question: "¿Qué onda?", answer: "¡Hola! ¿Qué tal todo?" },
    { question: "¿Cómo estás?", answer: "Estoy aquí para ayudarte con tus dudas." },
    { question: "Hola, ¿cómo estás?", answer: "¡Genial! Gracias por preguntar. ¿Y tú?" },
    { question: "¿Cómo va todo?", answer: "Todo marcha bien, gracias. ¿En qué te ayudo hoy?" },
    { question: "Hey, ¿qué pasa?", answer: "¡Hola! No mucho, aquí para ayudarte." },
    { question: "Hola, ¿hay alguien ahí?", answer: "¡Aquí estoy! ¿En qué necesitas ayuda?" },

    // **Despedidas**
    { question: "Adiós", answer: "¡Hasta pronto! Espero volver a verte." },
    { question: "Nos vemos", answer: "¡Nos vemos! Que tengas un buen día." },
    { question: "Chao", answer: "¡Chao! Cuídate." },
    { question: "Hasta luego", answer: "¡Hasta luego! Espero poder ayudarte de nuevo." },
    { question: "Gracias, adiós", answer: "¡De nada! Hasta pronto." },
    { question: "Me voy, adiós", answer: "¡Cuídate! Que tengas un excelente día." },
    { question: "Bye", answer: "¡Bye! Nos vemos pronto." },
    { question: "Hasta pronto", answer: "¡Hasta pronto! Aquí estaré cuando me necesites." },

    // **Preguntas sobre tecnología**
    { question: "¿Qué es inteligencia artificial?", answer: "La inteligencia artificial es una rama de la informática que busca crear sistemas capaces de realizar tareas que normalmente requieren inteligencia humana." },
    { question: "¿Qué es machine learning?", answer: "El machine learning es una rama de la IA que permite a las máquinas aprender de datos y mejorar su rendimiento con el tiempo." },
    { question: "¿Qué es una red neuronal?", answer: "Una red neuronal es un modelo computacional inspirado en el cerebro humano, utilizado en el aprendizaje profundo." },
    { question: "¿Qué es JavaScript?", answer: "JavaScript es un lenguaje de programación utilizado principalmente en el desarrollo web." },
    { question: "¿Qué es HTML?", answer: "HTML es un lenguaje de marcado que define la estructura de las páginas web." },
    { question: "¿Qué es CSS?", answer: "CSS es un lenguaje utilizado para diseñar y estilizar páginas web." },
    { question: "¿Qué es TensorFlow?", answer: "TensorFlow es una biblioteca de machine learning desarrollada por Google para construir y entrenar modelos." },
    { question: "¿Qué es React?", answer: "React es una biblioteca de JavaScript utilizada para construir interfaces de usuario interactivas." },
    { question: "¿Qué es una API?", answer: "Una API es una interfaz que permite a diferentes aplicaciones comunicarse entre sí." },
    { question: "¿Qué es Python?", answer: "Python es un lenguaje de programación conocido por su simplicidad y versatilidad." },
    { question: "¿Qué es un framework?", answer: "Un framework es una estructura predefinida que facilita el desarrollo de aplicaciones de software." },
    { question: "¿Qué es GitHub?", answer: "GitHub es una plataforma para alojar, colaborar y gestionar proyectos de software utilizando Git." },
    { question: "¿Qué es big data?", answer: "Big data se refiere a grandes conjuntos de datos que no pueden ser procesados por métodos tradicionales debido a su tamaño y complejidad." },
    { question: "¿Qué es un chatbot?", answer: "Un chatbot es un programa diseñado para simular conversaciones con usuarios." },
    { question: "¿Qué es cloud computing?", answer: "El cloud computing es el acceso a recursos informáticos a través de internet en lugar de servidores locales." },

    // **Preguntas sobre animales**
    { question: "¿Cuál es el animal más rápido?", answer: "El guepardo es el animal terrestre más rápido, alcanzando velocidades de hasta 112 km/h." },
    { question: "¿Qué animal vive más tiempo?", answer: "La almeja quahog oceánica puede vivir más de 500 años." },
    { question: "¿Cuál es el animal más grande del mundo?", answer: "La ballena azul es el animal más grande, alcanzando hasta 30 metros de largo." },
    { question: "¿Qué animal tiene mejor visión?", answer: "El camarón mantis tiene la visión más avanzada, con capacidad para ver luz ultravioleta y polarizada." },
    { question: "¿Cuál es el animal más inteligente?", answer: "Los delfines y los chimpancés se consideran algunos de los animales más inteligentes." },
    { question: "¿Qué animal duerme más?", answer: "El koala puede dormir hasta 22 horas al día." },
    { question: "¿Qué animal tiene más dientes?", answer: "El caracol gigante africano puede tener más de 25,000 dientes." },
    { question: "¿Cuál es el ave más veloz?", answer: "El halcón peregrino es el ave más veloz, alcanzando velocidades de hasta 389 km/h en picada." },
    { question: "¿Qué animal puede cambiar de color?", answer: "El camaleón y el pulpo pueden cambiar de color para camuflarse o comunicarse." },
    { question: "¿Qué animal tiene la mordida más fuerte?", answer: "El cocodrilo de agua salada tiene la mordida más fuerte, con una fuerza de 3,700 libras por pulgada cuadrada." },
    { question: "¿Cuántos corazones tiene un pulpo?", answer: "El pulpo tiene tres corazones." },
    { question: "¿Cómo se comunican las abejas?", answer: "Las abejas se comunican mediante un baile llamado 'danza de las abejas'." },
    { question: "¿Qué animal puede vivir sin agua por mucho tiempo?", answer: "El camello puede sobrevivir semanas sin agua al almacenar grasa en sus jorobas." },
    { question: "¿Qué animal pone más huevos?", answer: "El pez luna puede poner hasta 300 millones de huevos en una sola temporada." }
];
